### PR TITLE
playlist fix

### PR DESCRIPTION
**Pull request by sulphuring**
why make super efficient socket blaster 9000 when you waste it on trying playlist ids as videos lol

unrelated: this song i found sounds good https://www.youtube.com/watch?v=Ls6-JHduLoU

### CODE REVIEW

**Comment by h0nde** [comment]
no playlist ID follows the format of

**Comment by sulphuring** [comment]
yes that's what i'm saying, the program tries to use playlists as videos right now

**Comment by sulphuring** [comment]
oh yeah i'm retarded i was supposed to put `/playlist?list={target}`

**Comment by sulphuring** [comment]
but this works too because the video links show too in the sidebar

**Pull request closed without merging**
